language: java
env:
  matrix:
  - JDK=8
dist: trusty
matrix:
  allow_failures:
  - env: JDK=8-ea
deploy:
  provider: heroku
  api_key:
    secure: M1nrGOymBv77FthDQymdLCyFKvcS8kfOGZ0pTkQZPg0a+Fu6EMqZolrU9UqwL6Q78X+qARKqXV0H5WFjxwQaldY3DIpaoPAwAfbcGrwtT4dW0ZjnG605nRhSeVVawbHpcXLsoz3ncM67SeWDMybTAzY0y/qY6xpSpaWoQ712rLHOSs8dw/WEcIBNTpGtq+AHWojR+288QguTvr7Vu4lH7wptd+tEjjc1mmnE/SEXN+74UiE+Bsp9xYSyR1YDOMdW4hr7ye7RXKy2wFQRR9VRoDeibOiG6cLGnG+wFF5INjiNNO/KkWrIcjrEZxN+nrdQd/AscbJC2i4hDZMNTBeOiGKeDfK2SpeIQ38B/QwiXGVgxgFKYV6Nnmp2bvZwLbmU3BxnaRwdT+WDFwLLJnn+SWpG8GhVpmEE2PVkhu2RAo0HJgGNG69Ap/9jCkJ2mLtC0ik/mp/7UsLcRDNieQWJnO6k+ra6h7kLV4lLX3XGdVCY1hmYTRe+B59uIdo2sFcDuZY1eMTlJxZY83tMsiqCCedNM7+9dgFtnecYh3EOsi3+KneMjnZgGUzatqX9BslQ88zAKcK9urSa9fpzo+jbYkYSnvLCoXUjHQlPtF7rmPwII6Pyct4cBeUjK9ZlP8ILNjFy05ABU5VBv6ROVfAfAtfxtf21Ux+iRCXwNLvlsxI=
  app: hello
  on:
    repo: mrkansa/hello
